import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import {
  addHunt,
  advanceHuntProgress,
  archiveHunts,
  clearHuntProgress,
  deleteHunts,
  gcHunt,
  getAllHunts,
  getAllHuntsIncludingPrivate,
  getCreatorHunts,
  getFeaturedHunts,
  getHunt,
  getHuntById,
  getHuntClues,
  getHuntProgress,
  getHuntsByCreator,
  getSpotlightHunts,
  MAX_CLUES_PER_HUNT,
  restoreHuntStoreSnapshot,
  saveClueLocally,
  saveCluesLocallyBatch,
  setLocalFeaturedHunt,
  startHuntProgress,
  takeHuntStoreSnapshot,
  updateClueAnswer,
  updateHuntEndTime,
  updateHuntPromotion,
  updateHuntStatus,
} from "@/lib/huntStore";
import type { Clue, StoredHunt } from "@/lib/types";